[package]
name = "tz-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
cozy-chess = "0.3.3"
lazy_static = "1.4.0"

tch = "0.14.0"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = "1.0.188"
bytemuck = "1.14.0"
internal-iterator = "0.2.1"
serde_json = "1.0.107"
stopwatch = "0.0.7"
